### ISSUE TITLE
Tag latest release as 1.x

### ISSUE THREAD

**Issue by fsou** [umbrellio/laravel-common-objects#3]
Dear @pvsaintpe,

Releasing latest changes as 2.0.0 made the library as not being picked as dependency of larave-ltree, because the later requires laravel-common-objects matching 1.*.

I suggest to tag a new release with version matching the needed version for umbrellio/laravel-ltree considering that, in my understanding, there we're no breaking changes from this to the previous one.

Thank you.

**Comment by pvsaintpe** [comment]
@fsou 

Yes, this version of the package is not compatible with "umbrellio/laravel-ltree", I have already fixed this bug.

Will be available as soon as "umbrellio/laravel-ltree" is in 5.0.0.
Waiting for approvals: https://github.com/umbrellio/laravel-ltree/pull/31

I think it will take a few days.
