### ISSUE TITLE
hemp/presenter bug with laravel 9

### ISSUE THREAD

**Issue by noor-tg** [umbrellio/laravel-common-objects#6]
hi
hemp/presenter : `2.*` does not support laravel 9 but `dev-master` support it.
so if you change `hemp/presenter` to `dev-master` until new version added to support laravel 9 offically.

thank you

**Comment by pvsaintpe** [comment]
@nour-dev 

Check it out (https://github.com/umbrellio/laravel-common-objects/pull/7 ) and if everything is ok, please approve PR or comment this issue.

Thanks.

**Comment by noor-tg** [comment]
@pvsaintpe thank you
